name: Terraform S3

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region us-east-1

      - name: Create S3
        working-directory: terraform/s3-state
        run: |
          terraform init

      - name: Plan Terraform deployment
        working-directory: terraform/s3-state
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes
        working-directory: terraform/s3-state
        run: terraform apply -auto-approve tfplan
      
      - name: Clean up Terraform plan file
        working-directory: terraform/s3-state
        run: rm -rf tfplan
